nhfpc_v2/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('visualization.urls', namespace='dashboard')),
]

visualization/urls.py
#!/usr/bin/env python  
# encoding: utf-8  

""" 
@version: v1.0 
@author: 齐天亮
@license: Apache Licence  
@contact: qitianliang@outlook.com
@site: https://gitee.com/yongfeng006 
@software: PyCharm 
@file: urls.py 
@time: 2017/11/2 20:37 
"""
from django.conf.urls import url
from django.contrib.auth import views as auth
from . import views

auth.LoginView.extra_context = {'title': '登录'}
auth.LogoutView.extra_context = {'title': '登出'}


urlpatterns = [
    url(r'^login/', auth.LoginView.as_view(template_name='components/login.html'), name="login"),
    url(r'^logout/', auth.LogoutView.as_view(template_name='components/logout.html'), name="logout"),
    url(r'^questionnaires/$', views.questionnaires, name="questionnaires"),
    #TODO 临时的额外表单

    url(r'^extra/$', views.extra, name="extra"),



    url(r'^details/(\w+)/([0-9]+)$', views.detail_question, name='visualization', ),
    url(r'^update_answer_options',views.update_answer_options,name='update_answer_options'),
    url(r'^update_options_description',views.update_options_description,name='update_options_description'),
    url(r'^update_options_segment',views.update_options_segment,name='update_options_segment'),
    url(r'^create_options_description',views.create_options_description,name='create_options_description'),
    url(r'^delete_options_description',views.delete_options_description,name='delete_options_description'),
    url(r'^update_question_helper',views.update_question_helper,name='update_question_helper'),
    url(r'^stat_answer_hospital$',views.stat_answer_hospital,name='stat_answer_hospital'),
    url(r'^stat_answer_health$',views.stat_answer_health,name='stat_answer_health'),
    url(r'^stat_extra_rate$',views.stat_extra_rate,name='stat_extra_rate'),
    url(r'^stat_extra_rate_health$',views.stat_extra_rate_health,name='stat_extra_rate_health'),



#TODO 有时间改一下shit code
url(r'^questionnaires/data$', views.questionnaires_data,name="data"),

    #TODO 测试页面ui
    url(r'^test/',views.test,name='test'),
]

templates/components/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Xenon Boostrap Admin Panel for nhfpc"/>
    <meta name="author" content="qitianliang"/>

    <title>static visualization</title>

    <!-- <link rel="stylesheet" href="http://fonts.useso.com/css?family=Arimo:400,700,400italic"> -->
    <link rel="stylesheet" href="{% static 'css/fonts/linecons/css/linecons.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-core.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-components.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-skins.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->


</head>
<body class="page-body login-page">


<div class="login-container">

    <div class="row">

        <div class="col-sm-6">

            <script type="text/javascript">
                jQuery(document).ready(function ($) {
                    // Reveal Login form
                    setTimeout(function () {
                        $(".fade-in-effect").addClass('in');
                    }, 1);


                    // Validation and Ajax action
                    $("form#login").validate({
                        rules: {
                            username: {
                                required: true
                            },

                            password: {
                                required: true
                            }
                        },

                        messages: {
                            username: {
                                required: 'Please enter your username.'
                            },

                            password: {
                                required: 'Please enter your password.'
                            }
                        },

                        // Form Processing via AJAX
                    });

                    // Set Form focus
                    $("form#login .form-group:has(.form-control):first .form-control").focus();
                });
            </script>

            <!-- Errors container -->
            <div class="errors-container">



            </div>

            <!-- Add class "fade-in-effect" for login form effect -->
            <form method="post" role="form" id="login" class="login-form fade-in-effect"
                  action="{% url 'dashboard:login' %}">
                {% csrf_token %}

                <div class="login-header">
                    <a href="{% url 'dashboard:login' %}" class="logo">
                        <span><h1>国家卫生与计划生育委员会专题问卷结果可视化</h1></span>
                    </a>
                    <p>欢迎，请登录</p>
                </div>
                <div class="form-group">
                    <label class="control-label" for="username">Username</label>
                    <input type="text" class="form-control input-dark" name="username" id="username"
                           autocomplete="off"/>
                </div>

                <div class="form-group">
                    <label class="control-label" for="password">Password</label>
                    <input type="password" class="form-control input-dark" name="password" id="password"
                           autocomplete="off"/>
                </div>
                {% if form.errors %}
{#                    <script>#}
{#                    toastr.info('<i class=fa-info></i>Are you the 6 fingered man?');#}
{#                    </script>#}
                    <b style="color: red">用户和口令不匹配，请重试！</b>
                                        {% endif %}
                                        {% if next %}
                                            {% if user.is_authenticated %}
                                                用户所在组无权访问，请使用授权用户登录。
                                            {% else %}
                                                请先登录
                                            {% endif %}
                                        {% endif %}
                <div class="form-group">
                    <button type="submit" class="btn btn-dark  btn-block text-left">
                        <i class="fa-lock"></i>
                        登入
                    </button>
                </div>
{#                <input type="hidden" name="next" value="{{ next }}" />#}

                <div class="login-footer">
                    <a href="Mailto:qitianliang@outlook.com?Subject=forget password in nhfpc questionnaire visualization&Body=Dear admin,">
                        <i class="linecons-mail"></i>
                        忘记密码?联系管理员</a>

                    <div class="info-links">
                        <a href="#">XJTU</a> -
                        <a href="#">Provide</a>
                    </div>

                </div>

            </form>

            <!-- External login -->
            <!-- <div class="external-login">
                <a href="#" class="facebook">
                    <i class="fa-facebook"></i>
                    Facebook Login
                </a>

                <!--
                <a href="#" class="twitter">
                    <i class="fa-twitter"></i>
                    Login with Twitter
                </a>

                <a href="#" class="gplus">
                    <i class="fa-google-plus"></i>
                    Login with Google Plus
                </a>
                 -->
            <!-- </div> -->

        </div>

    </div>

</div>


<!-- Bottom Scripts -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/TweenMax.min.js' %}"></script>
<script src="{% static 'js/resizeable.js' %}"></script>
<script src="{% static 'js/joinable.js' %}"></script>
<script src="{% static 'js/xenon-api.js' %}"></script>
<script src="{% static 'js/xenon-toggles.js' %}"></script>
<script src="{% static 'js/jquery-validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/toastr/toastr.min.js' %}"></script>


<!-- JavaScripts initializations and stuff -->
<script src="{% static 'js/xenon-custom.js' %}"></script>

</body>
</html>

templates/components/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Xenon Boostrap Admin Panel for nhfpc"/>
    <meta name="author" content="qitianliang"/>

    <title>static visualization</title>

    <!-- <link rel="stylesheet" href="http://fonts.useso.com/css?family=Arimo:400,700,400italic"> -->
    <link rel="stylesheet" href="{% static 'css/fonts/linecons/css/linecons.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-core.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-components.css' %}">
    <link rel="stylesheet" href="{% static 'css/xenon-skins.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->


</head>
<body class="page-body login-page">


<div class="login-container">

    <div class="row">

        <div class="col-sm-6">

            <script type="text/javascript">
                jQuery(document).ready(function ($) {
                    // Reveal Login form
                    setTimeout(function () {
                        $(".fade-in-effect").addClass('in');
                    }, 1);


                    // Validation and Ajax action
                    $("form#login").validate({
                        rules: {
                            username: {
                                required: true
                            },

                            password: {
                                required: true
                            }
                        },

                        messages: {
                            username: {
                                required: 'Please enter your username.'
                            },

                            password: {
                                required: 'Please enter your password.'
                            }
                        },

                        // Form Processing via AJAX
                    });

                    // Set Form focus
                    $("form#login .form-group:has(.form-control):first .form-control").focus();
                });
            </script>

            <!-- Errors container -->
            <div class="errors-container">



            </div>

            <!-- Add class "fade-in-effect" for login form effect -->
            <form method="post" role="form" id="login" class="login-form fade-in-effect"
                  action="{% url 'dashboard:login' %}">
                {% csrf_token %}

                <div class="login-header">
                    <a href="{% url 'dashboard:login' %}" class="logo">
                        <span><h1>国家卫生与计划生育委员会专题问卷结果可视化</h1></span>
                    </a>
                    <p>欢迎，请登录</p>
                </div>
                <div class="form-group">
                    <label class="control-label" for="username">Username</label>
                    <input type="text" class="form-control input-dark" name="username" id="username"
                           autocomplete="off"/>
                </div>

                <div class="form-group">
                    <label class="control-label" for="password">Password</label>
                    <input type="password" class="form-control input-dark" name="password" id="password"
                           autocomplete="off"/>
                </div>
                {% if form.errors %}
                    <script>
                    toastr.info('<i class=fa-info></i>Are you the 6 fingered man?');
                    </script>
                    <b style="color: red">用户和口令不匹配，请重试！</b>
                                        {% endif %}
                                        {% if next %}
                                            {% if user.is_authenticated %}
                                                用户所在组无权访问，请使用授权用户登录。
                                            {% else %}
                                                请先登录
                                            {% endif %}
                                        {% endif %}
                <div class="form-group">
                    <button type="submit" class="btn btn-dark  btn-block text-left">
                        <i class="fa-lock"></i>
                        登入
                    </button>
                </div>
{#                <input type="hidden" name="next" value="{{ next }}" />#}

                <div class="login-footer">
                    <a href="Mailto:qitianliang@outlook.com?Subject=forget password in nhfpc questionnaire visualization&Body=Dear admin,">
                        <i class="linecons-mail"></i>
                        忘记密码?联系管理员</a>

                    <div class="info-links">
                        <a href="#">XJTU</a> -
                        <a href="#">Provide</a>
                    </div>

                </div>

            </form>

            <!-- External login -->
            <!-- <div class="external-login">
                <a href="#" class="facebook">
                    <i class="fa-facebook"></i>
                    Facebook Login
                </a>

                <!--
                <a href="#" class="twitter">
                    <i class="fa-twitter"></i>
                    Login with Twitter
                </a>

                <a href="#" class="gplus">
                    <i class="fa-google-plus"></i>
                    Login with Google Plus
                </a>
                 -->
            <!-- </div> -->

        </div>

    </div>

</div>


<!-- Bottom Scripts -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/TweenMax.min.js' %}"></script>
<script src="{% static 'js/resizeable.js' %}"></script>
<script src="{% static 'js/joinable.js' %}"></script>
<script src="{% static 'js/xenon-api.js' %}"></script>
<script src="{% static 'js/xenon-toggles.js' %}"></script>
<script src="{% static 'js/jquery-validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/toastr/toastr.min.js' %}"></script>


<!-- JavaScripts initializations and stuff -->
<script src="{% static 'js/xenon-custom.js' %}"></script>

</body>
</html>

templates/components/questionnaires.html
{% extends "components/base.html" %}
{% load staticfiles %}
{% block content %}

    <div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">问卷详细</h3>
            </div>
            <ul id="myTab" class="nav nav-tabs">
                {% for id,info in  questionnaires_list.items %}
                    {% if id == '36d06675-d061-4a1c-93df-1718fd267fff' %}
                        <li class="active">
                            {% else %}
                        <li>
                    {% endif %}
                <a href="#{{ id }}" data-toggle="tab"  class="table-striped table-bordered table-hover table-detail">{{ info.name }}</a>
                </li>
                {% endfor %}
            </ul>

            <div id="myTabContent" class="tab-content">
                {% for id,info in questionnaires_list.items %}
                    {% if id == '36d06675-d061-4a1c-93df-1718fd267fff' %}
                        <div id={{ id }} class="tab-pane fade in active">
                    {% else %}
                        <div id={{ id }} class="tab-pane fade">
                    {% endif %}
                    <table id={{ id }} data-toggle="table" class="table-striped table-bordered table-hover table-detail"
{#                           data-detail-view="true"#}
{#                           data-detail-formatter="detail is designing"#}
                           data-url="{% url 'dashboard:data' %}?id={{ id }}"
                    >
                        <thead>
                        <tr>
                            <th data-field="id">序号</th>
                            <th data-field="first_dir">一级目录</th>
                            <th data-field="second_dir">二级目录</th>
                            <th data-field="stem">题干</th>
                            <th data-field="type">类型</th>
                            <th data-field="options">选项/填空</th>
                        </tr>
                        </thead>
                    </table>
            </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static "js/custom/bootstrap-table.min.js" %}"></script>
    <script src="{% static "js/custom/bootstrap-table-editable.min.js" %}"></script>
    <script src="{% static "js/custom/bootstrap-editable.min.js" %}"></script>
    <script src="{% static "js/custom/bootstrap-table-export.js" %}"></script>
    <script src="{% static "js/custom/tableExport.js" %}"></script>
    <script src="{% static "js/custom/bootstrap-table-zh-CN.js" %}"></script>
    <script src="{% static 'js/custom/questionnaire.js' %}"></script>
{% endblock %}

templates/components/test.html
{% extends "components/base.html" %}
{% load staticfiles %}
{% block title %}
    测试页面
{% endblock %}